---
- hosts: all
  pre_tasks:
    - block:
        - name: Install paxctld
          apt:
            name: paxctld
        - name: Lay down pax flags for node
          lineinfile:
            regexp: "^/usr/share/kibana/node/bin/node"
            path: /etc/paxctld.conf
            line: "/usr/share/kibana/node/bin/node  m"
        - name: paxctld start service
          service:
            name: paxctld
            state: restarted
      when: ansible_kernel.endswith('grsec')
  roles:
    - role: freedomofpress.kibana
  vars:
    kibana_config_es:
      elasticsearch.url: "http://esserver:9200"
      elasticsearch.preserveHost: true
      elasticsearch.requestTimeout: 30000
    kibana_config_server:
      server.host: "0.0.0.0"
